### ISSUE TITLE
Autocompletion AJAX error with native CMS Pages

### ISSUE THREAD

**Issue by skripteria** [skripteria/wn-site-search-plugin#2]
With activated autocompletion in the search input component an AJAX error is generated:

![autocompletion](https://user-images.githubusercontent.com/67191102/137310081-f6c38f95-639b-49b3-9e71-c345d34f3e7f.png)

This happens only when the native CMS pages feature is active, Blog and Pages Plugin work fine.

This is highly related to [this issue](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/issues/57) , but none of the suggested fixes seem to work

**Comment by skripteria** [comment]
Found the cause:

In the CmsPagesResultsProvider.php it says:
`$contents = \Html::strip((new Controller())->runPage($page));`
when you change it to
`$contents = \Html::strip((new Controller())->runPage($page, false));`
the error stops.
Apparently this line triggered an AJAX conflict since the Controller runPage method defaults to $useAjax = true

**Comment by PubliAlex** [comment]
Can confirm the issue and the fix, can it be commited in a next release ?
